### PR TITLE
Migrate WBTC big DAO multisig to a new one with safer active signers

### PR DESCRIPTION
**Pull request by tranvictor**
### Issue

The current big DAO multisig (`0xd409db68d0e6e97e1cb1f3eb0bd38de278bc3c68`) has 18 signers and requires 11 to form a consensus and process a transaction. Now that nearly 4 years have passed, several of the original signers have become inactive and/or lost control of their keys which diminishes the availability of the multisig. It’s important that we are able to successfully process a vote in the event that any of the WBTC contract(s) needs be amended (replace custodian, upgrade/modify token contract, etc.).

### Solution
As a result, we are migrating the WBTC Big DAO (whose chief responsibility is to govern the Controller) to a new multi-sig contract with new members and an updated voting threshold. Here is a summary of the changes:

Old Big DAO Multi-sig: [0xd409db68d0e6e97e1cb1f3eb0bd38de278bc3c68](https://etherscan.io/address/0xd409db68d0e6e97e1cb1f3eb0bd38de278bc3c68#writeContract) will be deprecated.
New Big DAO Multi-sig: [0xB33f8879d4608711cEBb623F293F8Da13B8A37c5](https://etherscan.io/address/0xB33f8879d4608711cEBb623F293F8Da13B8A37c5#writeContract)

Previous members (18 seats, 11 votes required):

Project | Address
-- | --
Gopax | 0x6707a6763c6dc64de7c4048a27b6303292f88f50
Dharma | 0xf7c630ee2dfebe834a0473d4d98ddad2c514a392
Tom Bean | 0xc485cf598a2f0cd43adbbccf4eee85a182746e4e
Kyber | 0xfdf28bf25779ed4ca74e958d54653260af604c20
BitGo | 0x87d604ea0419815204361bf3025d016448ffd95d
Set | 0xf4b583293339425cf94203e186d097589af5a611
Prycto | 0x5aa0c20df887b11520e141e0cac9f56f207bf9b0
Nuo | 0x03d6c9a6e124a4cc002858936ceed05ce5df3ab8
Loopring | 0xd8056194369f71a98b82799132f71f34084f7660
MakerDAO | 0xd5d4ab76e8f22a0fdcef8f483cc794a74a1a928e
Gnosis: MultiSig 2 | 0x851b7f3ab81bd8df354f0d7640efcd7288553419
Ren | 0xc038c8850f73c4a8453dbf7c59447b397978d7ea
AirSwap | 0xfaf0708d1aed2566205d61f471d7e4aeb10910ea
DDEX | 0xf848405353889d352bd20db95c86d75ef2e75022
The Ocean | 0x02e6f32bf32948ccfc0ff30858ef6c02c9b6f507
OmiseGo | 0x8409dcfcbdb0a78930d87fb6c06bd8119bb94bf5
Compound | 0x185adb71ae202dfabb4146272186457e4e170523
Blockfolio (FTX) | 0x36dee7493cb4fdebbf6fd67be4d4ec559aa61fe1

New Members (13 seats, 8 votes required):

Project | Address
-- | --
B.Protocol/RiskDAO | 0xe27B57A99e5CAc0E0f16eE0d5D768126B05422A8
Badger | 0x86cbD0ce0c087b482782c181dA8d191De18C8275
Balancer | 0x512fce9B07Ce64590849115EE6B32fd40eC0f5F3
BitGo | 0x157b1e5ba2302308461f64a8606f2d5970df129e
Chainlink | 0x65CE9DC44591d3B35c6c47b0a42bAeB7191A9d11
Compound | 0x8B8592E9570E96166336603a1b4bd1E8Db20fa20
Gopax | 0x6707A6763c6Dc64DE7C4048A27b6303292F88F50
Krystal | 0xE71B29B60f60b8fc6dCeC56A16107fc1B919e530
Kyber | 0x8180a5CA4E3B94045e05A9313777955f7518D757
Loopring | 0x4CBbD41a2c057cAb8db00AC60f1AB52F36870185
Multichain | 0xa80F73b93526ef992B52E3998bb103a0a8f2359d
Ren | 0xF54cf21835A12c825adbE2cFfF87a08C5aa1D430
Tom Bean | 0xcBf19D8F01146e3Ec89Aed604485FAbEfA66B268

New Member Address Verification Tweets:

Project | Address
-- | --
B.Protocol/RiskDAO | https://twitter.com/Risk_DAO/status/1580277842356883457
Badger | https://twitter.com/BadgerDAO/status/1541437469736013824
Balancer | https://twitter.com/balancer/status/1535172352614572032
BitGo | https://twitter.com/BitGo/status/1524069347357954048
Chainlink | https://twitter.com/chainlink/status/1535035763321995264
Compound | https://twitter.com/compoundfinance/status/1561861362166505472
Gopax | https://twitter.com/GOPAX_kr/status/1084773803966644225
Krystal | https://twitter.com/KrystalDefi/status/1540343634645512197
Kyber | https://twitter.com/KyberNetwork/status/1439063988390612994
Loopring | https://twitter.com/loopringorg/status/1439069579662159883?s=20
Multichain | https://twitter.com/MultichainOrg/status/1541307609151467521
Ren | https://twitter.com/renprotocol/status/1580957330597851136
Tom Bean | https://twitter.com/tcbean/status/1527665509726052356

### What’s included in this Pull Request:

1. Change of the WBTC DAO's Readme
2. transferOwnership operation from Old Big DAO multisig to New Big DAO multisig:
2.1. Kyber initiated with [this transaction](https://etherscan.io/tx/0x33328753d1631ee0396a77bdcdea8377c2cfb288fa2d2304a54887fd53811ec2). The `transactionID` is 9
2.2. All required approvals are done
3. Multisig operation from the new DAO big multisig to claim ownership:
3.1. Bitgo initiated with [this transaction]( https://etherscan.io/tx/0xe1a0069a37390e287ca399a4ee79036660ac235da08cb86753045fe5d9e97acc). The `transactionID` is 0
3.2. All required approvals are done

### CODE REVIEW

**Comment by joekoh-bg** [comment]
### Issue

The current big DAO multisig (`0xd409db68d0e6e97e1cb1f3eb0bd38de278bc3c68`) has 18 signers and requires 11 to form a consensus and process a transaction. Now that nearly 4 years have passed, several of the original signers have become inactive and/or lost control of their keys which diminishes the availability of the multisig. It’s important that we are able to successfully process a vote in the event that any of the WBTC contract(s) needs be amended (replace custodian, upgrade/modify token contract, etc.).

### Solution
As a result, we are migrating the WBTC Big DAO (whose chief responsibility is to govern the Controller) to a new multi-sig contract with new members and an updated voting threshold. Here is a summary of the changes:

Old Big DAO Multi-sig: [0xd409db68d0e6e97e1cb1f3eb0bd38de278bc3c68](https://etherscan.io/address/0xd409db68d0e6e97e1cb1f3eb0bd38de278bc3c68#writeContract) will be deprecated.
New Big DAO Multi-sig: [0xB33f8879d4608711cEBb623F293F8Da13B8A37c5](https://etherscan.io/address/0xB33f8879d4608711cEBb623F293F8Da13B8A37c5#writeContract)

Previous members (18 seats, 11 votes required):

Project | Address
-- | --
Gopax | 0x6707a6763c6dc64de7c4048a27b6303292f88f50
Dharma | 0xf7c630ee2dfebe834a0473d4d98ddad2c514a392
Tom Bean | 0xc485cf598a2f0cd43adbbccf4eee85a182746e4e
Kyber | 0xfdf28bf25779ed4ca74e958d54653260af604c20
BitGo | 0x87d604ea0419815204361bf3025d016448ffd95d
Set | 0xf4b583293339425cf94203e186d097589af5a611
Prycto | 0x5aa0c20df887b11520e141e0cac9f56f207bf9b0
Nuo | 0x03d6c9a6e124a4cc002858936ceed05ce5df3ab8
Loopring | 0xd8056194369f71a98b82799132f71f34084f7660
MakerDAO | 0xd5d4ab76e8f22a0fdcef8f483cc794a74a1a928e
Gnosis: MultiSig 2 | 0x851b7f3ab81bd8df354f0d7640efcd7288553419
Ren | 0xc038c8850f73c4a8453dbf7c59447b397978d7ea
AirSwap | 0xfaf0708d1aed2566205d61f471d7e4aeb10910ea
DDEX | 0xf848405353889d352bd20db95c86d75ef2e75022
The Ocean | 0x02e6f32bf32948ccfc0ff30858ef6c02c9b6f507
OmiseGo | 0x8409dcfcbdb0a78930d87fb6c06bd8119bb94bf5
Compound | 0x185adb71ae202dfabb4146272186457e4e170523
Blockfolio (FTX) | 0x36dee7493cb4fdebbf6fd67be4d4ec559aa61fe1

New Members (13 seats, 8 votes required):

Project | Address
-- | --
B.Protocol/RiskDAO | 0xe27B57A99e5CAc0E0f16eE0d5D768126B05422A8
Badger | 0x86cbD0ce0c087b482782c181dA8d191De18C8275
Balancer | 0x512fce9B07Ce64590849115EE6B32fd40eC0f5F3
BitGo | 0x157b1e5ba2302308461f64a8606f2d5970df129e
Chainlink | 0x65CE9DC44591d3B35c6c47b0a42bAeB7191A9d11
Compound | 0x8B8592E9570E96166336603a1b4bd1E8Db20fa20
Gopax | 0x6707A6763c6Dc64DE7C4048A27b6303292F88F50
Krystal | 0xE71B29B60f60b8fc6dCeC56A16107fc1B919e530
Kyber | 0x8180a5CA4E3B94045e05A9313777955f7518D757
Loopring | 0x4CBbD41a2c057cAb8db00AC60f1AB52F36870185
Multichain | 0xa80F73b93526ef992B52E3998bb103a0a8f2359d
Ren | 0xF54cf21835A12c825adbE2cFfF87a08C5aa1D430
Tom Bean | 0xcBf19D8F01146e3Ec89Aed604485FAbEfA66B268

New Member Address Verification Tweets:

Project | Address
-- | --
B.Protocol/RiskDAO | https://twitter.com/Risk_DAO/status/1580277842356883457
Badger | https://twitter.com/BadgerDAO/status/1541437469736013824
Balancer | https://twitter.com/balancer/status/1535172352614572032
BitGo | https://twitter.com/BitGo/status/1524069347357954048
Chainlink | https://twitter.com/chainlink/status/1535035763321995264
Compound | https://twitter.com/compoundfinance/status/1561861362166505472
Gopax | https://twitter.com/GOPAX_kr/status/1084773803966644225
Krystal | https://twitter.com/KrystalDefi/status/1540343634645512197
Kyber | https://twitter.com/KyberNetwork/status/1439063988390612994
Loopring | https://twitter.com/loopringorg/status/1439069579662159883?s=20
Multichain | https://twitter.com/MultichainOrg/status/1541307609151467521
Ren | https://twitter.com/renprotocol/status/1580957330597851136
Tom Bean | https://twitter.com/tcbean/status/1527665509726052356

### What’s included in this Pull Request:

1. Change of the WBTC DAO's Readme
2. transferOwnership operation from Old Big DAO multisig to New Big DAO multisig:
2.1. Kyber initiated with [this transaction](https://etherscan.io/tx/0x33328753d1631ee0396a77bdcdea8377c2cfb288fa2d2304a54887fd53811ec2). The `transactionID` is 9
2.2 [More votes will be updated here]
3. Multisig operation from the new DAO big multisig to claim ownership:
3.1. Kyber initiated with this transaction [will be updated]
3.2. [More votes will be updated here]

**Comment by ravz** [comment]
this is great to hear, thank you @tranvictor

**Comment by marsrobertson** [comment]
One question that came to my mind - it is possible to add / remove / replace existing signers:

image

Since the new mulisig has been deployed + all the verification tweets were sent = my comment now is irrelevant 🤡

For the historical context (blockchain archeologists) why deploying new multisig if changing old is possible? Or maybe it is not?

> several of the original signers have become inactive and/or lost control of their keys which diminishes the availability of the multisig

image

Diminish as in "reduce redundancy" or diminish as in "we are completely f***ed up"?

**Comment by tranvictor** [comment]
@marsrobertson changing one by one of the old multisig is possible, however it takes huge effort for the whole DAO to vote on. The multisig doesn't allow batch modification, each `replace` and `remove` and `update requirement` will have to vote from at least 11 voters. It will take a lot of time. The faster approach is to migrate to a new multisig and keep the record of the old multisig in the docs and technically it is always available on the blockchain's historical state.

We are fine. Not fked in any ways.

**Comment by lukasschor** [comment]
Why not use the Safe contracts for the new Multisig? https://github.com/WrappedBTC/DAO/issues/14

It's definitely the most battle-tested Multisig contracts out there, allows for gas-less signatures, batch transaction (i.e. would solve issues like the one described [here](https://github.com/WrappedBTC/DAO/pull/12#issuecomment-1328207038)).

**Comment by ravz** [comment]
Hello can we please get an update on what's happening with this PR ?

**Comment by ravz** [comment]
any update on this please ?

**Comment by rggithubether** [comment]
@tranvictor pls include my issue with this PR thank u so much in advance. @ravz thank u for the support.

**Comment by rggithubether** [comment]
any update on this pls?  thank u in advance. 
https://github.com/WrappedBTC/bitcoin-token-smart-contracts/issues/50

**Comment by rggithubether** [comment]
hello @tranvictor  WBTC DAO,

pls help return my 0.04495 WBTC

**Comment by rggithubether** [comment]
any update on this please :( 
https://github.com/WrappedBTC/bitcoin-token-smart-contracts/issues/50 

Transaction hash:  0x1f1c8971dec959d38bcaa5606eb474d028617752240727692cd5ef21a435d847

**Comment by rggithubether** [comment]
@tranvictor thanks for the update.

**Comment by rggithubether** [comment]
hello, kindly let us know any update on this. thank you.

**Comment by rggithubether** [comment]
hi any update please?

**Comment by ElementalBrian** [comment]
Tom Bean lost the keys to his entire protocol, why the fuck would he be put on here? #BearishWBTC

**Pull request merged**
